# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacitacion', models.CharField(blank=True, choices=[('C', 'Crear y Emprender'), ('G', 'Gestionado de Empresa'), ('H', 'Habilidades blandas'), ('A', 'Alternativas de Financimiento'), ('T', 'Tic en Gestion Empresarial'), ('E', 'Asociatiidad Empresarial'), ('I', 'Inclusion Productiva')], max_length=1, null=True, verbose_name='Capacitacion')),
            ],
        ),
    ]
