# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='descripcion',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='Capacitacion: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='capacitacion',
            field=models.CharField(blank=True, choices=[('C', 'Crear y Emprender'), ('G', 'Gestionado de Empresa'), ('H', 'Habilidades blandas'), ('A', 'Alternativas de Financimiento'), ('T', 'Tic en Gestion Empresarial'), ('E', 'Asociatiidad Empresarial'), ('I', 'Inclusion Productiva')], max_length=1, null=True, verbose_name='Lista de Capacitacion: '),
        ),
    ]
