# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_auto_20171128_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('identificacion', models.CharField(choices=[('DNI', 'DNI'), ('CI', 'CI'), ('LC', 'LC')], max_length=3, verbose_name='Tipo de Identificacion')),
                ('numero', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('estadocivil', models.CharField(max_length=30, verbose_name='Estado Civil')),
                ('profesion', models.CharField(max_length=30, verbose_name='Profesion')),
                ('cuil', models.CharField(max_length=30, verbose_name='CUIL o CUIT')),
                ('capacitacion', models.ManyToManyField(to='expediente.Capacitacion')),
            ],
        ),
    ]
