# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0004_emprendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.CharField(choices=[('Asesoramiento', 'Asesoramiento'), ('Seguimiento: Credito', 'Seguimiento: Credito'), ('Seguimiento: Subsidio', 'Seguimiento: Subsidio'), ('Financiamiento: Propio', 'Financiamiento: Propio'), ('Financiamiento: Tercero', 'Financiamiento: Tercero'), ('Feria: Desafio Producir', 'Feria: Desafio Producir'), ('Feria: Paseo Artesano', 'Feria: Paseo Artesano'), ('Feria: Otros', 'Feria: Otros'), ('Capacitacion', 'Capacitacion'), ('No aprobado', 'No aprobado')], max_length=3, verbose_name='Asiento')),
                ('texto', models.TextField(verbose_name='Informacion del expediente: ')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='identificacion',
            field=models.CharField(choices=[('DNI', 'DNI (Documento Nacional de Identidad)'), ('CI', 'CI (Cedula de identidad)'), ('LC', 'LC (Libreta de enrolamiento)')], default='DNI', max_length=3, verbose_name='Tipo de Identificacion'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='emprendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Emprendedor'),
        ),
    ]
