# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0005_auto_20171128_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='asiento',
            field=models.CharField(choices=[('Asesoramiento', 'Asesoramiento'), ('Seguimiento: Credito', 'Seguimiento: Credito'), ('Seguimiento: Subsidio', 'Seguimiento: Subsidio'), ('Financiamiento: Propio', 'Financiamiento: Propio'), ('Financiamiento: Tercero', 'Financiamiento: Tercero'), ('Feria: Desafio Producir', 'Feria: Desafio Producir'), ('Feria: Paseo Artesano', 'Feria: Paseo Artesano'), ('Feria: Otros', 'Feria: Otros'), ('Capacitacion', 'Capacitacion'), ('No aprobado', 'No aprobado')], max_length=25, verbose_name='Asiento'),
        ),
    ]
