# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0006_auto_20171128_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
