# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0007_auto_20171129_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de carga: '),
        ),
    ]
