# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0010_auto_20171130_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.CharField(choices=[('ASESORAMIENTO', 'ASESORAMIENTO'), ('SEGUIMIENTO: CREDITO', 'SEGUIMIENTO: CREDITO'), ('SEGUIMIENTO: SUBSIDIO', 'SEGUIMIENTO: SUBSIDIO'), ('FINANCIAMIENTO: PROPIO', 'FINANCIAMIENTO: PROPIO'), ('FINANCIAMIENTO: TERCERO', 'FINANCIAMIENTO: TERCERO'), ('FERIA: DESAFIO PRODUCIR', 'FERIA: DESAFIO PRODUCIR'), ('FERIA: PASEO ARTESANO', 'FERIA: PASEO ARTESANO'), ('FERIA: OTROS', 'FERIA: OTROS'), ('CAPACITACION', 'CAPACITACION'), ('NO APROBADO', 'NO APROBADO')], max_length=25, verbose_name='Asiento')),
            ],
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='numero',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='capacitacion8',
            field=models.ManyToManyField(to='expediente.Capacitacion8'),
        ),
    ]
