# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 08:49
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0011_auto_20171130_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendedor',
            name='capacitacion1',
        ),
        migrations.RemoveField(
            model_name='emprendedor',
            name='capacitacion2',
        ),
        migrations.RemoveField(
            model_name='emprendedor',
            name='capacitacion3',
        ),
        migrations.RemoveField(
            model_name='emprendedor',
            name='capacitacion4',
        ),
        migrations.RemoveField(
            model_name='emprendedor',
            name='capacitacion5',
        ),
        migrations.RemoveField(
            model_name='emprendedor',
            name='capacitacion6',
        ),
        migrations.RemoveField(
            model_name='emprendedor',
            name='capacitacion7',
        ),
        migrations.RemoveField(
            model_name='emprendedor',
            name='capacitacion8',
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='asiento',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ASESORAMIENTO', 'ASESORAMIENTO'), ('SEGUIMIENTO: CREDITO', 'SEGUIMIENTO: CREDITO'), ('SEGUIMIENTO: SUBSIDIO', 'SEGUIMIENTO: SUBSIDIO'), ('FINANCIAMIENTO: PROPIO', 'FINANCIAMIENTO: PROPIO'), ('FINANCIAMIENTO: TERCERO', 'FINANCIAMIENTO: TERCERO'), ('FERIA: DESAFIO PRODUCIR', 'FERIA: DESAFIO PRODUCIR'), ('FERIA: PASEO ARTESANO', 'FERIA: PASEO ARTESANO'), ('FERIA: OTROS', 'FERIA: OTROS'), ('CAPACITACION', 'CAPACITACION'), ('NO APROBADO', 'NO APROBADO')], default=1, max_length=187),
            preserve_default=False,
        ),
    ]
