# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-03 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0013_auto_20171202_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='usuario',
            field=models.CharField(default=1, max_length=30, verbose_name='Responsable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='cuil',
            field=models.CharField(max_length=13, verbose_name='CUIL o CUIT'),
        ),
    ]
