# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-06 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0015_auto_20171206_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendedor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='usuario',
            field=models.CharField(default=1, max_length=30, verbose_name='Responsable'),
            preserve_default=False,
        ),
    ]
