# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-06 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0016_auto_20171206_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprendedor',
            name='estadocivil',
            field=models.CharField(choices=[('SOLTERO/A', 'SOLTERO/A'), ('COMPROMETIDO/A', 'COMPROMETIDO/A'), ('CASADO/A', 'CASADO/A'), ('DIVORCIADO/A', 'DIVORCIADO/A'), ('VIUDO/A', 'VIUDO/A')], max_length=14, verbose_name='Estado Civil'),
        ),
    ]
