# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-06 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0017_auto_20171206_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='rubro',
            field=models.CharField(choices=[('Rubro1', 'Rubro1'), ('Rubro2', 'Rubro2'), ('Rubro3', 'Rubro4'), ('Rubro5', 'Rubro5'), ('Rubro6', 'Rubro6')], default=1, max_length=15, verbose_name='Rubro'),
            preserve_default=False,
        ),
    ]
