# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0018_expediente_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendedor',
            name='fecha',
            field=models.DateField(default="2017-01-01", verbose_name='Fecha de carga: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprendedor',
            name='numero',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
