# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0019_auto_20171210_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendedor',
            name='creador',
            field=models.CharField(default='2015-01-01', max_length=30, verbose_name='Creador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprendedor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
