# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-10 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0020_auto_20171210_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprendedor',
            name='creador',
        ),
    ]
