# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-12 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0021_remove_emprendedor_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='rubro',
            field=models.CharField(choices=[('ARTESANO', 'ARTESANO'), ('DISEÑO', 'DISEÑO'), ('GASTRONOMICO', 'GASTRONOMICO'), ('HORTICOLA', 'HORTICOLA'), ('SERVICIOS', 'SERVICIOS'), ('SUSTENTABILIDAD', 'SUSTENTABILIDAD'), ('TAXI/REMIS', 'TAXI/REMIS'), ('TECNOLOGIA APROPIADA', 'TECNOLOGIA APROPIADA'), ('TECNOLOGICO', 'TECNOLOGICO')], max_length=15, verbose_name='Rubro'),
        ),
    ]
